name: Run myed tests
on:
  push:
    branches:
    - master
    paths:
    - getting-credits/2019/**
    - .github/workflows/myed.yml
jobs:
  job1:
    name: GNU ed on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Checkout stef
      uses: actions/checkout@v2
      with:
        repository: devnull-cz/stef
        path: stef
    - name: Run the tests
      run: ./dev/myed.sh
