name: Refresh notes
on:
  push:
    branches:
    - master
    paths:
    - modules/*
    - .github/workflows/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install pre-requisites
      run: npm install markdown-include
    - name: Expand MarkDown files
      # should use 'npm root -g' instead of hard-coded path
      run: /usr/local/lib/node_modules/markdown-include/bin/cli.js input/2020/*.json
