name: Compile source code
on:
  push:
    branches:
    - master
    paths:
    - src/*
    - dev/compile_src.sh
    - .github/workflows/src.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Install gcc
      run: sudo apt-get install gcc
    - name: Compile source code
      run: ./dev/compile_src.sh
